# Python CircleCI 2.0 configuration file
##
# Check https://circleci.com/docs/2.0/language-python/ for more details


version: 2
jobs:
  build-docker:
    environment:
      IMAGE_NAME: remdelaportemathurin/test
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASS
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:temp .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login
            docker push $IMAGE_NAME:temp

  test:
    environment:
      IMAGE_NAME: remdelaportemathurin/test
    docker:
      - image: $IMAGE_NAME:temp
    working_directory: ../
    steps:

      - run:
          name: run utils tests
          command: |
            ls
            pytest test.py

workflows:
  version: 2
  build-test:
    jobs:
      - build-docker
      - test:
          requires:
            - build-docker
